export const Types = {
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORYSUCCESS",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    GET_ONE_CATEGORY_SUCCESS: "GET_ONE_CATEGORY_SUCCESS",
    ADD_PRODUCT_SUCCESS:"ADD_PRODUCT_SUCCESS",
    DELETE_PRODUCT_SUCCESS:"DELETE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_SUCCESS:"UPDATE_PRODUCT_SUCCESS",
    GET_ONE_PRODUCT_SUCCESS: "GET_ONE_PRODUCT_SUCCESS",
}
